version: '3'
services:
  chatapp:
    container_name: chatapp
    image: namonak/chatapp:0.0.6
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_ENDPOINT=http://localhost:8088
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - 8088:8080
    restart: always
