version: '3'
services:
  chatapp:
    container_name: chatapp
    image: namonak/chatapp:0.0.4
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_ENDPOINT=http://localhost:8088
    ports:
      - 8088:8080
    restart: always
